Fixed a bug at line 468 of libphox.py where the response would be in bytes and frombuffer would be unable to convert to an array.
This seems to be a python 2 vs python 3 issue. frombuffer can't directly
convert bytes anymore.

Bug example

In [2]: switch.connect(port='A',contact=1)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[2], line 1
----> 1 switch.connect(port='A',contact=1)

File ~\Desktop\Qubic\QphoX\CryoSwitchController\CryoSwitchController.py:666, in Cryoswitch.connect(self, port, contact)
    663     if self.debug:
    664         print(f'Connecting Port:{port}, Contact {contact}')
--> 666     current_profile = self.select_and_pulse(port, contact, 1)
    667     return current_profile
    668 else:

File ~\Desktop\Qubic\QphoX\CryoSwitchController\CryoSwitchController.py:523, in Cryoswitch.select_and_pulse(self, port, contact, polarity)
    521 selection_result = self.select_output_channel(port, contact, polarity)
    522 if selection_result:
--> 523     current_profile = self.send_pulse()
    524     self.disable_output_channels()
    525     if self.plot:

File ~\Desktop\Qubic\QphoX\CryoSwitchController\CryoSwitchController.py:423, in Cryoswitch.send_pulse(self)
    420     print('WARNING: Timing protection triggered, resetting...')
    421     self.reset_output_supervisor()
--> 423 current_data = self.labphox.application_cmd('pulse', 1)
    425 return current_data * self.get_current_gain()

File ~\Desktop\Qubic\QphoX\CryoSwitchController\libphox.py:468, in Labphox.application_cmd(self, cmd, value)
    464 if self.compare_cmd(cmd, 'pulse'):
    465     ##self.serial_com.flushInput()
    466     ##response = self.communication_handler('W:3:T:' + str(value) + ';', standard=False)
    467     response = self.packet_handler('W:3:T:' + str(value) + ';')
--> 468     return np.fromstring(response, dtype=np.uint8)
    470 elif self.compare_cmd(cmd, 'acquire'):
    471     response = self.communication_handler('W:3:Q:' + str(value) + ';')

ValueError: The binary mode of fromstring is removed, use frombuffer instead